version: "3.9" 

name: "3x03-Team17-debug"

services:
  react:
    image: react
    build:  
        dockerfile: ./client/Dockerfile
    ports:
     - "3000:3000"
  flask:
    image: flask
    network: 3x03-team17-debug_default
    build:
        dockerfile: ./server/Dockerfile
    ports:
      - "5000:80"




