version: "3.9" 

name: "3x03-Team17-debug"

services:
  react:
    image: react
    build:  
        dockerfile: ./client/Dockerfile
    ports:
     - "3001:3000"
  flask:
    image: flask
    build:
    command: python app.py run -h 0.0.0.0
        dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"




