version: "3.9" 

name: "3x03-Team17-debug"

services:
  react:
    image: react
    container_name: reacts
    build:  
        dockerfile: ./client/Dockerfile
    ports:
     - "3000:3000"
  flask:
    image: flask
    container_name: flasks
    build:
        dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"




