version: "3.9" 

services:
  react:
    image: react
    build: ./client #build the docker file inside the client directory
    ports:
     - "3000:3000"
  flask:
    image: flask
    build: ./server #build the docker file inside the  server directory
    ports:
      - "5000:5000"

